AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for Prowler automation

Resources:
  IAMRoleForProwler:
    Type: AWS::IAM::Role
    Properties:
      RoleName: audit-prowler-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::111111111111:root
            Action: 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess